#!/bin/bash
SCRIPT_DIR=$(realpath $(dirname "$0"))
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install -r requirements.txt
echo "Installation complete. Please create your .env file and add this folder to path."